### ISSUE TITLE
add welcome message when someone joins the server

### ISSUE THREAD

**Issue by darkChozo** [darkChozo/FAbot#18]
should be easy, discord.py has a on_member_join event

**Comment by mdennehy** [comment]
We just want to be careful about spam levels. 
Honestly, we might want to have two bots in the channel ultimately - same code, different config, one as FA_bot and one as Aziz_bot and keep all the humour in Aziz_bot so that FA_bot is dull, boring and never muted 'cos the stuff it does post is functional and useful.

**Comment by Boberro** [comment]
And what about Azoz bot, the only necessary bot?
